export const HEADER_HEIGHT = '56px'
export const HEADER_DROPDOWN_TOP = '48px'
export const SIDEBAR_WIDTH = '240px'

export const SHOW_LOADING_DELAY_SECONDS = 0.1
export const SHOW_LOADING_DELAY_MS = SHOW_LOADING_DELAY_SECONDS * 1000
